// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxgd_ps5sRUqsfo4HHRhkvdwx5JZhPwIM',
    appId: '1:670087647110:web:436de259dfa48295ff6607',
    messagingSenderId: '670087647110',
    projectId: 'taskapp-fa0d8',
    authDomain: 'taskapp-fa0d8.firebaseapp.com',
    storageBucket: 'taskapp-fa0d8.firebasestorage.app',
    measurementId: 'G-6HGHNT9RF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_cVsuaJ2dvdajK4hCmPhOcmDy5QuR7k',
    appId: '1:670087647110:android:7d5e47eab7138b41ff6607',
    messagingSenderId: '670087647110',
    projectId: 'taskapp-fa0d8',
    storageBucket: 'taskapp-fa0d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLRczUo4pKO2W02lWvlPHkd6PcFvKXMGY',
    appId: '1:670087647110:ios:9bf4da77fdd48385ff6607',
    messagingSenderId: '670087647110',
    projectId: 'taskapp-fa0d8',
    storageBucket: 'taskapp-fa0d8.firebasestorage.app',
    iosClientId: '670087647110-h6th80gqrvve3nrl6qomppbgk2ckrgdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsTheMove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLRczUo4pKO2W02lWvlPHkd6PcFvKXMGY',
    appId: '1:670087647110:ios:9bf4da77fdd48385ff6607',
    messagingSenderId: '670087647110',
    projectId: 'taskapp-fa0d8',
    storageBucket: 'taskapp-fa0d8.firebasestorage.app',
    iosClientId: '670087647110-h6th80gqrvve3nrl6qomppbgk2ckrgdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsTheMove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxgd_ps5sRUqsfo4HHRhkvdwx5JZhPwIM',
    appId: '1:670087647110:web:ff6a735df5a0487bff6607',
    messagingSenderId: '670087647110',
    projectId: 'taskapp-fa0d8',
    authDomain: 'taskapp-fa0d8.firebaseapp.com',
    storageBucket: 'taskapp-fa0d8.firebasestorage.app',
    measurementId: 'G-GMRPLBJQRH',
  );
}
